add mobile view
PrinceBadru/mobilefirst pull request #1
Opened 2023-01-12 18:19 UTC by PrinceBadru

## MOBILE FIRST.
 - Add html.
 - Add css.
 - Add readme.
 - add linters.

2023-01-12 18:31 UTC, NahnahAJ reviewed
Hi @PrinceBadru , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a well set up README file and you are missing some of your linter files.

- Please make sure to use the [Microverse Readme template](https://github.com/microverseinc/readme-template). Since you didn't add it, this makes your project incomplete. Every section of the readme template is required with the exception of the FAQ section which is optional. So please make sure to add all the sections in the template to your project and fill in all the necessary contents :+1:

- You can follow these instructions to help customize it to suit this project:

    • Remove the Microverse logo. If you have your logo, you can use it but I would advise you to remove it :100: 

    • For the Tech Stack Section, Kindly remove the Server and Database subsections because the technologies listed there are not relevant to this project. For the Client section, kindly include HTML and CSS :+1: 

    • For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. :wink: 

    • For the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
        ◦ Installation of Git
        ◦ Installation of NPM
        ◦ A working browser
        ◦ Internet connection
        ◦ A code editor like Visual Studio Code
        ◦ Installation of Live Server plugging in Visual Studio Code
        ◦ Any other tool you can think about :100: 

    • For the Setup section, kindly add instructions for cloning your repository on a local machine :+1: 

    • For the Install section, kindly add instructions for setting up linters used in this project :+1: 

    • For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.

- For the Future Features section include 2 or more future features

- Lastly, make sure your MIT license link is not broken.

-  Kindly implement all the changes listed above. It will make your README.md file look professional and it will give you an idea of how to set README.md files for most of the projects you will execute as a Microverse student.  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 09:14 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @PrinceBadru , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ]  [ ] [OPTIONAL]  kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-13 09:14 UTC, MaganaAsiati commented on index.html
> +    </section>
- You did a great job by adding the card section and contact form however they have not yet part of the requirement please remove them you will work on it in the next project :+1:

2023-01-13 09:14 UTC, MaganaAsiati commented on index.html
> +        <script src="main.js" type="text/javascript"></script>
- [ ] Kindly the type script tag because you don't need any javascript implementation at this level :+1:

2023-01-13 09:14 UTC, MaganaAsiati commented on index.html
> +    <section class="second">
- kindly I suggest you reduce a bit the font size of the text in this section and make sure that the disposition of elements looks exactly like it is shown in the Figma design .your design must look as much as possible in the Figma design :+1: 

## Your design 
![image](https://user-images.githubusercontent.com/95297251/212280131-bfabb872-828e-4334-8063-f8ad5e8a3518.png)

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/212280301-10f9a27f-0b30-4398-974a-525ddb65c065.png)

2023-01-13 09:14 UTC, MaganaAsiati commented on index.html
> +        <div class="first-img" id="hamburger" > <img src="./images/Union.png" alt="a union of three vectors"> </div>
- [ ] Kindly make sure that the hamburger button has a nav tag. The nav tag is for semantics reasons. :+1:

2023-01-13 09:14 UTC, MaganaAsiati commented on index.html
> +        <div class="dash"></div>
- Kindly remove this part as it have not yet required to build desktop version or to implement Umberger button functionality  :+1:

2023-01-13 12:26 UTC, osamaashraf6 requested changes
Hi @PrinceBadru  ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Descriptive READme file in a professional way.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. ✔️👨🏻‍💻

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 12:26 UTC, osamaashraf6 commented on index.html
> +        <div class="dash"></div>
- [ ] As stated 😃 by the previous reviewer, it is not necessary to add this part now because this is from the requirements of the desktop version, so kindly remove this part now.💯

2023-01-13 12:26 UTC, osamaashraf6 commented on index.html
> +    <section class="second">
- [ ] As stated 😃 here by the previous reviewer, the font size of h1 and p is not like the Figma 👌I see that you give the gave the h1 and p tags property size: of 40px and 20px but it is not working💯, so try to write it like font-size not size only to let it work 👍

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212319546-3c3c32a5-8ed9-423f-836b-da06651a0db2.png) | ![image](https://user-images.githubusercontent.com/83360636/212319315-2b2b909c-6f98-431b-b48a-3296f7141bd8.png) |

2023-01-13 15:10 UTC, Debas-31 requested changes
> ## Hi @PrinceBadru :wave:, 
# Status: Require Change :recycle:
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"/>

 ## Highlights
- No linters error :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- PR title and summary :heavy_check_mark: 
- Commit message :heavy_check_mark:
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 15:10 UTC, Debas-31 commented on index.html
> +        <div class="first-img" id="hamburger" > <img src="./images/Union.png" alt="a union of three vectors"> </div>
- [ ] Great job implementing the code review suggestion, but the hamburger menu does not wrap on the navbar for semantic reasons, as the previous code reviewer suggested.

2023-01-13 15:10 UTC, Debas-31 commented on index.html
> +    <section class="second">
- [ ] Good job on implementing the previous code review suggestions; while you were implementing the tips, you missed the alignment in your design. Please kindly fix :hammer_and_pick: the alignment to be identical to the Figma template design that you choose.

***Your design***
![Screenshot from 2023-01-13 16-37-12](https://user-images.githubusercontent.com/65129228/212348878-2392b89c-007e-47c4-9b00-6fcf32c9b105.png)

***Figma template design***
![Screenshot from 2023-01-13 17-37-47](https://user-images.githubusercontent.com/65129228/212349104-2f54c52e-0dae-45b7-96dd-8d4ad353a24f.png)

2023-01-13 17:06 UTC, PrinceBadru commented
@Debas-31 can you give me more details please

2023-01-14 12:24 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @PrinceBadru, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 10:41 UTC, merged