new desktop changes
PrinceBadru/mobilefirst pull request #4
Opened 2023-01-21 11:28 UTC by PrinceBadru

##Desktop changes
 -Add media queries.
 -Add flexbox.
 -add  font, colors, images, text, margins.

2023-01-21 13:12 UTC, NahnahAJ requested changes
Hi @PrinceBadru, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Professional README :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- Nice Design :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Starting your commit messages with a capital letter
eg. **Added mobile menu**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 13:12 UTC, nahnahdev commented on style.css
> +@media (min-width: 678px) {
- Great job building your project gradually to this stage well done :wink: There are just a few changes we have to make in order to get the project to meet all the project requirements :+1: 
- [x] Great job-making use of media queries but I noticed that the `min-width` you applied doesn't meet the project requirements. I have attached a screenshot of the project requirements regarding the media queries below so you can refer to it and fix this accordingly :+1: 
![image](https://user-images.githubusercontent.com/102699958/213865694-3a72bfd6-17cf-42fd-b194-cfac54afdcfc.png)

2023-01-21 13:12 UTC, nahnahdev commented on style.css
>    }
- Great job styling this part :100:, However,  it seems like you forgot to add the `Get my resume` button that was present in the Figma design. Kindly add the button so all the project requirements can be well met :wink: 
- Your design
![image](https://user-images.githubusercontent.com/102699958/213866259-9bf0cbc2-cf04-4607-8b5e-6f4ace1470ab.png)

- The Figma design
![image](https://user-images.githubusercontent.com/102699958/213866292-2a6965f6-e731-4e47-b253-aba300c03da7.png)

2023-01-21 13:12 UTC, nahnahdev commented on style.css
>      border-radius: 10px;
- [x] I noticed here that these shapes don't have the right background color and border applied like what was in the Figma design. In this Figma design the background color was, `background: #EBF0EE;` and the border was `border: 1px solid #C1C7D0;` Please refer to the Figma template and apply the required styles to this part of the project. :wink:
- [x] I also noticed that in the Figma design, the shapes were styled as squares but from the image below yours looks more rectangular in shape. Kindly fix this as well. I suggest you use the exact styles that were used in the Figma Design guidelines :100: You can see from the image below that they have a `height: 369px` and `width: 352px;` :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/213866806-4543b7e3-2cab-48df-955d-9c18368b46cc.png)
-The Figma Design
![image](https://user-images.githubusercontent.com/102699958/213867022-7d9cda36-9945-40e9-9035-efe9b54d5837.png)

- [x] The styles for the list of languages used in the project have a bigger border-radius than the Figma design. I will suggest you refer to the Figma design and apply the right border-radius to your list of items. Per the project requirements, you are to ensure that you follow the Figma design as much as possible :wink: 
- [x] The spaces between the elements should also look similar to that of the Figma design :+1: 
- [x] Kindly repeat this for all the other buttons in the other cards as well :+1: 
![image](https://user-images.githubusercontent.com/102699958/213867372-07370aa6-eef2-434e-ba87-f5991e93c8cd.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/213867389-81884cc9-0a9f-412d-b402-4c5903ba45b8.png)

2023-01-21 13:12 UTC, NahnahAJ commented on style.css
>    }
- Great job arranging your project cards :100: , However, I noticed that the size of your cards doesn't match that of the Figma design. I have attached screenshots below.
- Your design
![image](https://user-images.githubusercontent.com/102699958/213867853-1be0e74b-5943-44d4-bd02-89eaa16b06f3.png)
- From the image and your styles above, you can see that your design has a width of 327px and a height of 474px. But in the Figma Design, the width is 369px instead. Kindly fix this as well :wink: 
![image](https://user-images.githubusercontent.com/102699958/213868082-4d219332-e493-4dd4-87dd-05cd548514ee.png)

2023-01-21 21:21 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @PrinceBadru 

Excellent job implementing the changes suggested by previous reviewer. 
**_However, I there are just very few things left that needs to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Well done so far following the given Figma design
- ✅ Great job with CSS
- ✅ Good job with PR and README
- ✅ Correct Linters

However, there is always room for improvement.

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] I think it would be better if you remove the `placeholders` from each section in your README file. These placeholders are present for your guidance of what to put in that section. We don't want our reader to get confused of these things. Right? What do you think ? 🎯

![image](https://user-images.githubusercontent.com/106119105/213887308-4ff0e39c-16d1-4a3d-9194-e52dc81209d0.png)


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 21:21 UTC, KanzaTahreem commented on style.css
> +
Excellent job adding the **_Get my Resume_** `button`. However, there are still few things to fix 🔽
- [ ] You have made a great effort adding a `hover` effect. Great work 👍 Please make sure that you follow the [figma template's](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=BMXPZecvl1PksERT-0) button interaction so that we have a design close to figma template as much as possible.

## **_Your design previously 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886224-dd726332-17a0-4feb-afc2-d7d60365d71c.png)

## **_Your design now 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886214-70f5be02-05f3-439b-90a4-4101cae4a90e.png)

## **_Figma template 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886205-6010c06d-9288-4736-ad91-3ef9ac8ad375.png)

2023-01-21 21:21 UTC, KanzaTahreem commented on style.css
Excellent job done with the cards 👍. Well done fixing the border and radius💪 Let's fix the things that are left.
- [ ] Please make sure that cards look exactly like the one present in figma template. Also, I noticed that you are using `background-color: #e2e6ee`. But in figma template it is `background-color: #ebf0ee`. Please fix this 😄
- [ ] Let's make sure that the list of languages are styled exactly according to the figma template as suggested earlier. Although you have used the correct `border-radius` but still the design of list of languages is not according to the one provided in figma template and which was advised by previous reviewer. I know you can fix this one. Right ?💪

## **_Your design previously 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886862-e0066ac8-ca03-4b2c-a40a-23e91f7df451.png)

## **_Your design now 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886855-ffd1f276-cff7-4658-87ef-4e46ebef6204.png)

## **_Figma design 👇_**
![image](https://user-images.githubusercontent.com/106119105/213886874-d5370962-d2d4-4e4e-9950-86c84e911798.png)

2023-01-21 21:42 UTC, PrinceBadru commented on style.css
@KanzaTahreem no can you please help me?

2023-01-21 21:42 UTC, PrinceBadru commented on style.css
@KanzaTahreem give me more detail please

2023-01-21 21:44 UTC, PrinceBadru commented on style.css
I  got it its fine

2023-01-21 22:39 UTC, vickymarz requested changes
Hi @PrinceBadru, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- You seems to have a visible horizontal scroll ball on your website which is not a good user experience. Kindly fix it 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/213889793-74d0e858-7543-490c-8d67-fe217cb1fa51.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 22:39 UTC, vickymarz commented on style.css
> +  }
- [ ] Good job trying to include the button interaction 👍🏽 . Kindly note that the hover state button interaction has a box shadow that you didn't add. Kindly add it to all your buttons 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/213889647-fcb0b192-c81a-460d-91fd-b8068f7b1f06.png)

2023-01-21 23:22 UTC, AlphaNtihinduka requested changes
## Hi @PrinceBadru 🙋‍♂️

Good job working on implementing the changes required by the previous reviewers. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- Kindly consider the inline comments, and apply the changes required to ensure that the page is more professional to recruiters.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-01-21 23:22 UTC, AlphaNtihinduka commented on style.css
> +  }
- [ ] I have noticed that the background image may be one of the causes of the Horizontal scroll 😞 . The experience of scrolling horizontally can make the screen judder and create a headache-inducing feeling 😞 . As the previous reviewer suggested. Kindly ensure that there is no horizontal scroll in the entire application screen size. 👍 

- Consider the screenshot for reference. 😎 
![horizontal scroll](https://user-images.githubusercontent.com/99394374/213892770-3f7ebfb4-8cd6-4306-a122-c85cb66edf47.PNG)

2023-01-21 23:22 UTC, AlphaNtihinduka commented on style.css
>    }
- [ ] [OPTIONAL] To ensure that your project looks more professional, you should stick to the Figma file 👌 . Please make sure that the  `width` is slightly bigger than the `height` of the card 😎 .

2023-01-23 11:24 UTC, Lameck1 reviewed
Hello @PrinceBadru  👋,

_This is an additional review as a result of the second opinion request._

The suggestions by the previous reviewer were okay. However since you have addressed them, consider this project complete. 

All the best with the next project.

Keep rocking 🚀!

2023-01-23 12:33 UTC, KanzaTahreem commented on style.css
Hello @PrinceBadru, I can see that you have done really well. Great job 👍. 
Sundays are usually off that's why I was unable to reply.
Congratulations for fixing this👏 Keep going

2023-01-23 14:31 UTC, merged